language: android
jdk: oraclejdk8

addons:
  apt:
    packages:
      - lynx

android:
 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-27
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27
before_install:
- yes | sdkmanager "platforms;android-27"
script:
    - ./gradlew build check
after_script:
- if [ -f /home/travis/build/adrcotfas/Goodtime/app/build/outputs/lint-results-debug.html ]; then lynx -dump /home/travis/build/adrcotfas/Goodtime/app/build/outputs/lint-results-debug.html; fi
