---
files:
  # Compose Multiplatform resources (commonMain)
  - source: "composeApp/src/commonMain/composeResources/values/strings_about.xml"
    translation: "composeApp/src/commonMain/composeResources/values-%android_code%/%original_file_name%"
    labels:
      - about
  - source: "composeApp/src/commonMain/composeResources/values/strings_backup.xml"
    translation: "composeApp/src/commonMain/composeResources/values-%android_code%/%original_file_name%"
    labels:
      - backup
  - source: "composeApp/src/commonMain/composeResources/values/strings_intro.xml"
    translation: "composeApp/src/commonMain/composeResources/values-%android_code%/%original_file_name%"
    labels:
      - intro
  - source: "composeApp/src/commonMain/composeResources/values/strings_labels.xml"
    translation: "composeApp/src/commonMain/composeResources/values-%android_code%/%original_file_name%"
    labels:
      - labels
  - source: "composeApp/src/commonMain/composeResources/values/strings_settings.xml"
    translation: "composeApp/src/commonMain/composeResources/values-%android_code%/%original_file_name%"
    labels:
      - settings
  - source: "composeApp/src/commonMain/composeResources/values/strings_stats.xml"
    translation: "composeApp/src/commonMain/composeResources/values-%android_code%/%original_file_name%"
    labels:
      - statistics
  - source: "composeApp/src/commonMain/composeResources/values/strings_support.xml"
    translation: "composeApp/src/commonMain/composeResources/values-%android_code%/%original_file_name%"
    labels:
      - support

  # Android-specific resources (ACRA crash reporting strings)
  - source: "composeApp/src/androidMain/res/values/strings_main.xml"
    translation: "composeApp/src/androidMain/res/values-%android_code%/%original_file_name%"
    labels:
      - main
      - acra
      - android-only